name: native-google-cloud-run
on:
  push:
    paths:
      - 'native-google-cloud-run/**'
      - '.github/workflows/native-google-cloud-run.yml'
  pull_request:
    paths:
      - 'native-google-cloud-run/**'
      - '.github/workflows/native-google-cloud-run.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-google-cloud-run'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - version: 'latest'
            java-version: '17'
          - version: 'dev'
            java-version: '17'
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: ${{ matrix.java-version }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'native-google-cloud-run'
        run: |
          cd native-google-cloud-run
          ./mvnw package -Dpackaging=docker-native

